source 'http://rubygems.org'

gem 'rails', '3.0.6'
gem 'rake', '~> 0.8.7'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3-ruby', :require => 'sqlite3'
gem 'pg'
gem 'devise'
gem 'haml'
gem 'hpricot'
gem 'fakeweb'
gem 'mechanize'
gem 'delayed_job'

#gem "formageddon", '0.0.0', :path => "/Users/aross/pcf-work/gitbranches/formageddon"


group :test do
  gem 'cucumber-rails'
  gem 'capybara'
  gem 'database_cleaner'
  gem 'cucumber'
  gem 'rspec-rails'
  gem 'spork'
  gem 'webrat'
  gem 'firewatir'
end

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug'

# Bundle the extra gems:
# gem 'bj'
# gem 'nokogiri'
# gem 'sqlite3-ruby', :require => 'sqlite3'
# gem 'aws-s3', :require => 'aws/s3'

# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:
# group :development, :test do
#   gem 'webrat'
# end
